"""Add enhanced Booking fields and BlockedSlot model

Revision ID: 6a2c75806db5
Revises: 59dd16e7eabf
Create Date: 2026-02-18 10:42:51.716948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2c75806db5'
down_revision = '59dd16e7eabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('patient_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('patient_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referral_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referral_doctor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('referral_doctor')
        batch_op.drop_column('referral_type')
        batch_op.drop_column('patient_address')
        batch_op.drop_column('patient_email')
        batch_op.drop_column('patient_phone')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
